name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  my_first_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: list file
      run: ls -ltr
    - name: read file
      run: cat Dockerfile
    - name: creating file
      run: echo " i am good at github actions" > github

  second_job:
    
    runs-on: ubuntu-latest

    steps:
      needs: my_first_job

      