name: matrix

on:
  push:
    branches: [ "main" ]

jobs:

  my_first_job:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        images: [hello-world, alpine]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: docker info
        run: docker info

      - name: run image
        run: docker run ${{ matrix.images }}

